package me.collebol.input;

public enum KeyType {
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,
    ESCAPE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    GRAVE_ACCENT, MINUS, EQUAL, BACKSPACE, TAB, LEFT_BRACKET, RIGHT_BRACKET,
    BACKSLASH, SEMICOLON, APOSTROPHE, ENTER, COMMA, PERIOD, SLASH,
    SPACE, CAPS_LOCK, LEFT_SHIFT, RIGHT_SHIFT, LEFT_CONTROL, RIGHT_CONTROL,
    LEFT_ALT, RIGHT_ALT, LEFT_SUPER, RIGHT_SUPER, MENU,
    INSERT, DELETE, HOME, END, PAGE_UP, PAGE_DOWN,
    ARROW_UP, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT,
    NUM_LOCK, NUMPAD_0, NUMPAD_1, NUMPAD_2, NUMPAD_3, NUMPAD_4, NUMPAD_5,
    NUMPAD_6, NUMPAD_7, NUMPAD_8, NUMPAD_9, NUMPAD_DECIMAL, NUMPAD_DIVIDE,
    NUMPAD_MULTIPLY, NUMPAD_SUBTRACT, NUMPAD_ADD, NUMPAD_ENTER
}
