name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos, windows]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Deploy
        run: |
          echo "Building and deploying for ${{ matrix.os }} platform"
          # Bouw het project
          mvn --batch-mode clean package -P${{ matrix.os }}
          
          # Deploy het geshade artifact naar GitHub Packages
          mvn --batch-mode deploy:deploy-file \
            -Dfile=target/ejgengine-${{ github.event.release.tag_name }}-${{ matrix.os }}-shaded.jar \
            -DpomFile=pom.xml \
            -DgroupId=me.collebol \
            -DartifactId=ejgengine \
            -Dversion=${{ github.event.release.tag_name }}-${{ matrix.os }} \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/ColleBoll/EJGEngine
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

